export const STOPS = [
  {
    id: 'bac',
    num: '01',
    label: 'Bachelor of Computer Application (BCA)',
    short: 'Atmiya Institute',
    loc: 'Rajkot, India',
    yr: '2021 – 2024',
    desc: 'Built a strong core foundation in computer science, focusing on data structures, database management systems, and foundational programming languages.',
    icon: '🎓',
    era: 'EDUCATION',
    side: 'left',
    accent: '#818356',
    accentRgb: '129, 131, 86',
    bg0: '#0f172a',
    bg1: '#151412',
    gridCol: 'rgba(245,240,232,0.03)',
    particleCols: ['#818356', '#9ba06d', '#6d6f46'],
    image: '/images/atmiya.png',
  },
  {
    id: 'mca',
    num: '02',
    label: 'Master of Computer Applications (MCA)',
    short: 'SVIT, GTU',
    loc: 'Ahmedabad, Gujarat',
    yr: '2024 – 2026',
    desc: 'Advanced academic coursework in enterprise software development, specializing in system design, scalable backend architectures, and modern web technologies.',
    icon: '🎓',
    era: 'EDUCATION',
    side: 'right',
    accent: '#9ba06d',
    accentRgb: '155, 160, 109',
    bg0: '#0f172a',
    bg1: '#11100f',
    gridCol: 'rgba(245,240,232,0.04)',
    particleCols: ['#818356', '#aeb182', '#c3c5a0'],
    image: '/images/GTULogo-scaled.jpg',
  },
  {
    id: 'sde1',
    num: '03',
    label: 'Software Engineer Intern',
    short: 'Nomos Insights',
    loc: 'Surat, Gujarat',
    yr: 'Feb 2025 - Present',
    desc: 'Contributing to the development of robust backend services and RESTful APIs using Java and Spring Boot while collaborating on full-stack architecture optimizations.',
    icon: '💼',
    era: 'PROFESSIONAL',
    side: 'left',
    accent: '#f5f0e8',
    accentRgb: '245, 240, 232',
    bg0: '#0f172a',
    bg1: '#181714',
    gridCol: 'rgba(245,240,232,0.05)',
    particleCols: ['#f5f0e8', '#e5dfd3', '#ffffff'],
    image: '/images/nomos.jpg',
  },
];
